/* This file is automatically generated by the DailyBuild script. */
/* VERSION_STRING is the build's posting, ie. MXXX, Daily, Midday. */
/* VERSION_INT is the last successful major (MXXX) with the letter prefix (M) dropped. */
#if defined(GAME_FREE_VER)
  #define VERSION_STRING	_T("C000")
  #define VERSION_INT		0
#elif defined(GAME_VER)
  #define VERSION_STRING	_T("G000")
  #define VERSION_INT		0
#elif defined(WEBVERSION)
  #define VERSION_STRING	_T("M000")
  #define VERSION_INT		0
#elif defined DESIGN_VER
  #define VERSION_STRING	_T("B000")
  #define VERSION_INT		0
#else // MAX
  #define VERSION_STRING	_T("Luna L093 07-18-2002")
  #define VERSION_INT		93
#endif
